import { RoleType } from '@/types/role';

// Permission definitions for granular access control based on use case matrix
export const PERMISSIONS = {
  // Cost Reports (Báo cáo chi phí) - asc_manager should NOT have access
  'reports.cost.read': ['super_admin', 'company_admin', 'asc_admin'],
  'reports.cost.export': ['super_admin', 'company_admin', 'asc_admin'],

  // Model Error Reports (Báo cáo Model nhiều lỗi) - More accessible than cost reports
  'reports.model_error.read': [
    'super_admin',
    'company_admin',
    'asc_admin',
    'asc_manager',
    'asc_coordinator',
    'general_warehouse_manager',
    'admin_level_1',
    'company_customer_service',
  ],
  'reports.model_error.export': [
    'super_admin',
    'company_admin',
    'asc_admin',
    'asc_manager',
    'asc_coordinator',
    'general_warehouse_manager',
    'admin_level_1',
    'company_customer_service',
  ],

  // Category Error Reports (Báo cáo lỗi theo danh mục) - RESTRICTED ACCESS ONLY
  'reports.category_error.read': ['super_admin', 'company_admin'],
  'reports.category_error.export': ['super_admin', 'company_admin'],

  // Department Error Reports (Báo cáo lỗi theo nơi mua) - RESTRICTED ACCESS ONLY
  'reports.department_error.read': ['super_admin', 'company_admin'],
  'reports.department_error.export': ['super_admin', 'company_admin'],
  // AS Service Reports (Báo cáo dịch vụ AS)
  'reports.as_service.read': ['super_admin', 'company_admin'],
  'reports.as_service.export': ['super_admin', 'company_admin'],

  // Accessory Reports (Báo cáo linh kiện)
  'reports.accessory.read': ['super_admin', 'company_admin', 'asc_admin'],
  'reports.accessory.export': ['super_admin', 'company_admin', 'asc_admin'],

  // Total Warehouse stock export (Kho tổng)
  'reports.total_warehouse.export': [
    'super_admin',
    'company_admin',
    'general_warehouse_manager',
  ],

  // Sub-warehouse (ASC) stock export
  'reports.sub_warehouse.export': ['super_admin', 'company_admin', 'asc_admin'],
  // New permission name aligned with ascCenter export route
  'reports.asc_center.export': ['super_admin', 'company_admin', 'asc_admin'],

  // User management (Người dùng)
  'users.create': [
    'super_admin',
    'company_admin',
    'admin_level_1',
    'asc_admin',
    'asc_manager',
  ],
  'users.read': [
    'super_admin',
    'company_admin',
    'general_warehouse_manager',
    'admin_level_1',
    'asc_admin',
    'asc_manager',
    'asc_coordinator',
    'asc_technician',
    'asc_warehouse',
  ],
  'users.update': [
    'super_admin',
    'company_admin',
    'admin_level_1',
    'asc_admin',
    'asc_manager',
  ],
  'users.delete': ['super_admin', 'company_admin', 'asc_admin'],
  'users.assign_roles': ['super_admin', 'company_admin', 'asc_admin'],

  // Repair case management (Phiếu sửa chữa) - Enhanced granular permissions
  'repair_cases.create': [
    'super_admin',
    'company_admin',
    'admin_level_1',
    'asc_admin',
    'asc_manager',
    'asc_coordinator',
    'company_customer_service',
  ],
  'repair_cases.read': [
    'super_admin',
    'company_admin',
    'general_warehouse_manager',
    'admin_level_1',
    'asc_admin',
    'asc_manager',
    'asc_coordinator',
    'asc_technician',
    'asc_warehouse',
    'company_customer_service',
    'call_center',
  ],
  'repair_cases.update': [
    'super_admin',
    'company_admin',
    'admin_level_1',
    'asc_admin',
    'asc_manager',
    'asc_coordinator',
    'asc_technician',
  ],
  'repair_cases.delete': ['super_admin', 'company_admin', 'asc_admin'],
  'repair_cases.approve': ['super_admin', 'company_admin', 'asc_admin'],
  'repair_cases.assign': ['super_admin', 'company_admin', 'asc_admin'],
  'repair_cases.status_change': [
    'super_admin',
    'company_admin',
    'admin_level_1',
    'asc_admin',
    'asc_manager',
    'asc_coordinator',
    'asc_technician',
    'company_customer_service',
  ],
  'repair_cases.history': [
    'super_admin',
    'company_admin',
    'general_warehouse_manager',
    'admin_level_1',
    'asc_admin',
    'asc_manager',
    'asc_coordinator',
    'asc_technician',
    'asc_warehouse',
    'company_customer_service',
    'call_center',
  ],
  'repair_cases.parts_supply': [
    'super_admin',
    'company_admin',
    'general_warehouse_manager',
    'admin_level_1',
    'asc_admin',
    'asc_manager',
    'asc_technician',
    'asc_warehouse',
  ],
  'repair_cases.parts_update': [
    'super_admin',
    'company_admin',
    'general_warehouse_manager',
    'admin_level_1',
    'asc_admin',
    'asc_manager',
    'asc_technician',
    'asc_warehouse',
  ],
  'repair_cases.images_upload': [
    'super_admin',
    'company_admin',
    'general_warehouse_manager',
    'admin_level_1',
    'asc_admin',
    'asc_manager',
    'asc_coordinator',
    'asc_technician',
    'company_customer_service',
  ],
  'repair_cases.images_update': [
    'super_admin',
    'company_admin',
    'general_warehouse_manager',
    'admin_level_1',
    'asc_admin',
    'asc_manager',
    'asc_coordinator',
    'asc_technician',
    'company_customer_service',
  ],
  'repair_cases.cost_view': [
    'super_admin',
    'company_admin',
    'admin_level_1',
    'asc_admin',
    'asc_manager',
    'asc_coordinator',
  ],
  'repair_cases.cost_edit': [
    'super_admin',
    'company_admin',
    'asc_admin',
    'asc_manager',
  ],
  'repair_cases.warranty_cost_override': [
    'super_admin',
    'company_admin',
    'asc_admin',
    'asc_manager',
  ],

  // Customer management (Khách hàng)
  'customers.create': [
    'super_admin',
    'company_admin',
    'admin_level_1',
    'asc_admin',
    'asc_manager',
    'asc_coordinator',
    'company_customer_service',
  ],
  'customers.read': [
    'super_admin',
    'company_admin',
    'general_warehouse_manager',
    'admin_level_1',
    'asc_admin',
    'asc_manager',
    'asc_coordinator',
    'asc_technician',
    'asc_warehouse',
    'company_customer_service',
    'call_center',
  ],
  'customers.update': [
    'super_admin',
    'company_admin',
    'admin_level_1',
    'asc_admin',
    'asc_manager',
    'company_customer_service',
  ],
  'customers.delete': ['super_admin', 'company_admin'],

  // General Warehouse Management (Quản lý kho tổng) - Company level only
  'warehouse.general.parts.create': [
    'super_admin',
    'company_admin',
    'general_warehouse_manager',
  ],
  'warehouse.general.parts.read': [
    'super_admin',
    'company_admin',
    'general_warehouse_manager',
    'admin_level_1',
    'asc_admin',
    'asc_manager',
    'asc_warehouse',
    'asc_technician',
  ],
  'warehouse.general.parts.update': [
    'super_admin',
    'company_admin',
    'general_warehouse_manager',
  ],
  'warehouse.general.parts.delete': [
    'super_admin',
    'company_admin',
    'general_warehouse_manager',
  ],

  // ASC Warehouse Management (Quản lý kho ASC) - Center level
  'warehouse.asc.inventory.read': [
    'super_admin',
    'company_admin',
    'general_warehouse_manager',
    'admin_level_1',
    'asc_admin',
    'asc_manager',
    'asc_coordinator',
    'asc_warehouse',
    'asc_technician',
  ],
  'warehouse.asc.inventory.update': [
    'super_admin',
    'company_admin',
    'general_warehouse_manager',
    'asc_admin',
    'asc_manager',
    'asc_warehouse',
  ],
  'warehouse.asc.transfer.read': [
    'super_admin',
    'company_admin',
    'general_warehouse_manager',
    'admin_level_1',
    'asc_admin',
    'asc_manager',
    'asc_coordinator',
    'asc_warehouse',
  ],
  'warehouse.asc.transfer.create': [
    'super_admin',
    'company_admin',
    'general_warehouse_manager',
    'asc_admin',
    'asc_manager',
    'asc_warehouse',
  ],
  'warehouse.asc.return.create': [
    'super_admin',
    'company_admin',
    'general_warehouse_manager',
    'asc_admin',
    'asc_manager',
    'asc_warehouse',
  ],
  'warehouse.asc.stock_adjust': [
    'super_admin',
    'company_admin',
    'general_warehouse_manager',
    'asc_admin',
    'asc_manager',
    'asc_warehouse',
  ],

  // Legacy inventory permissions (for backward compatibility)
  'inventory.create': [
    'super_admin',
    'company_admin',
    'general_warehouse_manager',
    'asc_admin',
    'asc_manager',
    'asc_warehouse',
  ],
  'inventory.read': [
    'super_admin',
    'company_admin',
    'general_warehouse_manager',
    'admin_level_1',
    'asc_admin',
    'asc_manager',
    'asc_coordinator',
    'asc_technician',
    'asc_warehouse',
  ],
  'inventory.update': [
    'super_admin',
    'company_admin',
    'general_warehouse_manager',
    'asc_admin',
    'asc_manager',
    'asc_warehouse',
  ],
  'inventory.delete': ['super_admin', 'company_admin', 'asc_admin'],
  'inventory.approve': [
    'super_admin',
    'company_admin',
    'asc_admin',
    'asc_manager',
  ],
  'inventory.stock_adjust': [
    'super_admin',
    'company_admin',
    'general_warehouse_manager',
    'asc_admin',
    'asc_manager',
    'asc_warehouse',
  ],

  // Purchase orders
  'purchase_orders.create': [
    'super_admin',
    'company_admin',
    'asc_admin',
    'asc_warehouse',
  ],
  'purchase_orders.read': [
    'super_admin',
    'company_admin',
    'general_warehouse_manager',
    'admin_level_1',
    'asc_admin',
    'asc_manager',
    'asc_warehouse',
  ],
  'purchase_orders.update': [
    'super_admin',
    'company_admin',
    'asc_admin',
    'asc_warehouse',
  ],
  'purchase_orders.approve': ['super_admin', 'company_admin', 'asc_admin'],

  // Accessory requests
  'accessory_requests.create': [
    'super_admin',
    'company_admin',
    'asc_admin',
    'asc_technician',
    'asc_warehouse',
  ],
  'accessory_requests.read': [
    'super_admin',
    'company_admin',
    'general_warehouse_manager',
    'admin_level_1',
    'asc_admin',
    'asc_manager',
    'asc_coordinator',
    'asc_technician',
    'asc_warehouse',
  ],
  'accessory_requests.approve': ['super_admin', 'company_admin', 'asc_admin'],
  'accessory_requests.bulk_create': [
    'super_admin',
    'company_admin',
    'asc_admin',
    'asc_manager',
    'asc_warehouse',
  ],
  'accessory_requests.partial_approve': [
    'super_admin',
    'company_admin',
    'general_warehouse_manager',
  ],

  // Broadcast notifications
  'broadcasts.create': ['super_admin', 'company_admin'],
  'broadcasts.read': ['super_admin', 'company_admin'],
  'broadcasts.delete': ['super_admin', 'company_admin'],
  'broadcasts.stats': ['super_admin', 'company_admin'],

  // Warranty Centers (Trung tâm bảo hành) - Distinct from warranty operations
  'warranty_centers.create': ['super_admin', 'company_admin'],
  'warranty_centers.read': ['super_admin', 'company_admin'],
  'warranty_centers.update': ['super_admin', 'company_admin'],
  'warranty_centers.delete': ['super_admin', 'company_admin'],

  // Warranty management (operations)
  'warranty.create': [
    'super_admin',
    'company_admin',
    'asc_admin',
    'asc_coordinator',
    'asc_technician',
  ],
  'warranty.read': [
    'super_admin',
    'company_admin',
    'general_warehouse_manager',
    'admin_level_1',
    'asc_admin',
    'asc_manager',
    'asc_coordinator',
    'asc_technician',
    'asc_warehouse',
  ],
  'warranty.update': [
    'super_admin',
    'company_admin',
    'asc_admin',
    'asc_coordinator',
    'asc_technician',
  ],
  'warranty.approve': ['super_admin', 'company_admin', 'asc_admin'],
  'warranty.register': [
    'super_admin',
    'company_admin',
    'asc_admin',
    'asc_coordinator',
    'asc_technician',
  ],
  'warranty.transfer': ['super_admin', 'company_admin', 'asc_admin'],
  'warranty.void': ['super_admin', 'company_admin', 'asc_admin'],
  'warranty.escalate': [
    'super_admin',
    'company_admin',
    'asc_admin',
    'asc_coordinator',
    'asc_technician',
  ],

  // Financial operations
  'finance.read': [
    'super_admin',
    'company_admin',
    'admin_level_1',
    'asc_admin',
    'asc_manager',
  ],
  'finance.update': [
    'super_admin',
    'company_admin',
    'admin_level_1',
    'asc_admin',
    'asc_manager',
  ],
  'finance.approve': ['super_admin', 'company_admin', 'asc_admin'],

  // Appointments
  'appointments.create': [
    'super_admin',
    'company_admin',
    'asc_admin',
    'asc_coordinator',
    'asc_technician',
  ],
  'appointments.read': [
    'super_admin',
    'company_admin',
    'general_warehouse_manager',
    'admin_level_1',
    'asc_admin',
    'asc_manager',
    'asc_coordinator',
    'asc_technician',
    'asc_warehouse',
  ],
  'appointments.update': [
    'super_admin',
    'company_admin',
    'asc_admin',
    'asc_coordinator',
    'asc_technician',
  ],
  'appointments.delete': ['super_admin', 'company_admin', 'asc_admin'],

  // System administration
  'system.configure': ['super_admin'],
  'system.backup': ['super_admin'],
  'system.logs': ['super_admin', 'company_admin', 'asc_admin'],
  'system.users_manage': ['super_admin'],

  // Product Categories (Sản phẩm) - Separate from models
  'products.categories.create': ['super_admin', 'company_admin'],
  'products.categories.read': ['super_admin', 'company_admin'],
  'products.categories.update': ['super_admin', 'company_admin'],
  'products.categories.delete': ['super_admin', 'company_admin'],

  // Models - Enhanced with proper role access
  'models.create': ['super_admin', 'company_admin'],
  'models.read': [
    'super_admin',
    'company_admin',
    'admin_level_1',
    'asc_admin',
    'asc_manager',
    'asc_coordinator',
    'company_customer_service',
    'asc_warehouse',
  ],
  'models.update': ['super_admin', 'company_admin'],
  'models.delete': ['super_admin', 'company_admin'],

  // Legacy admin data management (for backward compatibility)
  'admin.categories.create': ['super_admin', 'company_admin'],
  'admin.categories.read': ['super_admin', 'company_admin', 'asc_admin'],
  'admin.categories.update': ['super_admin', 'company_admin'],
  'admin.categories.delete': ['super_admin', 'company_admin'],
  'admin.models.create': ['super_admin', 'company_admin'],
  'admin.models.read': [
    'super_admin',
    'company_admin',
    'admin_level_1',
    'asc_admin',
    'asc_manager',
    'asc_coordinator',
    'company_customer_service',
    'asc_warehouse',
  ],
  'admin.models.update': ['super_admin', 'company_admin'],
  'admin.models.delete': ['super_admin', 'company_admin'],
  'admin.error_phenomena.create': ['super_admin', 'company_admin'],
  'admin.error_phenomena.read': ['super_admin', 'company_admin', 'asc_admin'],
  'admin.error_phenomena.update': ['super_admin', 'company_admin'],
  'admin.error_phenomena.delete': ['super_admin', 'company_admin'],
  'admin.reasons.create': ['super_admin', 'company_admin'],
  'admin.reasons.read': ['super_admin', 'company_admin', 'asc_admin'],
  'admin.reasons.update': ['super_admin', 'company_admin'],
  'admin.reasons.delete': ['super_admin', 'company_admin'],
  'admin.purchase_locations.create': ['super_admin', 'company_admin'],
  'admin.purchase_locations.read': [
    'super_admin',
    'company_admin',
    'asc_admin',
    'asc_manager',
    'asc_coordinator',
    'asc_technician',
    'asc_warehouse',
    'company_customer_service',
    'call_center',
    'admin_level_1',
    'general_warehouse_manager',
  ],
  'admin.purchase_locations.update': ['super_admin', 'company_admin'],
  'admin.purchase_locations.delete': ['super_admin', 'company_admin'],
  'admin.solutions.create': ['super_admin', 'company_admin', 'asc_admin'],
  'admin.solutions.read': ['super_admin', 'company_admin', 'asc_admin'],
  'admin.solutions.update': ['super_admin', 'company_admin', 'asc_admin'],
  'admin.solutions.delete': ['super_admin', 'company_admin'],

  // Admin repair case management permissions
  'admin.repair_cases.read': [
    'super_admin',
    'company_admin',
    'asc_admin',
    'call_center',
  ],
  'admin.repair_cases.transfer': ['super_admin', 'company_admin', 'asc_admin'],
  'admin.repair_cases.quotation': ['super_admin', 'company_admin', 'asc_admin'],
  'admin.repair_cases.satisfaction': [
    'super_admin',
    'company_admin',
    'asc_admin',
    'asc_technician',
  ],
  'admin.repair_cases.assessment': [
    'super_admin',
    'company_admin',
    'asc_admin',
    'asc_technician',
  ],
  'admin.repair_cases.assign': ['super_admin', 'company_admin', 'asc_admin'],

  // Admin technician management permissions
  'admin.technicians.create': ['super_admin', 'company_admin', 'asc_admin'],
  'admin.technicians.read': ['super_admin', 'company_admin', 'asc_admin'],
  'admin.technicians.update': ['super_admin', 'company_admin', 'asc_admin'],
  'admin.technicians.delete': ['super_admin', 'company_admin'],

  // Admin area management permissions
  'admin.areas.create': ['super_admin'],
  'admin.areas.read': ['super_admin', 'company_admin', 'asc_admin'],
  'admin.areas.update': ['super_admin'],
  'admin.areas.delete': ['super_admin'],

  // Admin employee management permissions
  'admin.employees.create': ['super_admin', 'company_admin', 'asc_admin'],
  'admin.employees.read': ['super_admin', 'company_admin', 'asc_admin'],
  'admin.employees.update': ['super_admin', 'company_admin', 'asc_admin'],
  'admin.employees.delete': ['super_admin', 'company_admin'],
  'admin.asc_centers.create': ['super_admin', 'company_admin'],
  'admin.asc_centers.read': [
    'super_admin',
    'company_admin',
    'asc_admin',
    'asc_manager',
    'asc_coordinator',
    'asc_technician',
    'company_customer_service',
    'call_center',
    'admin_level_1',
    'general_warehouse_manager',
    'asc_warehouse',
  ],
  'admin.asc_centers.update': ['super_admin', 'company_admin', 'asc_admin'],
  'admin.asc_centers.delete': ['super_admin', 'company_admin'],
  'admin.inventory.purchase_orders': ['super_admin', 'company_admin'],
  'admin.inventory.distributions': ['super_admin', 'company_admin'],
  'admin.inventory.returns': ['super_admin', 'company_admin', 'asc_admin'],
  'admin.system.analytics': ['super_admin', 'company_admin', 'asc_admin'],
  'admin.system.reports': ['super_admin', 'company_admin', 'asc_admin'],

  // Add new permissions to PERMISSIONS object:

  // Sub-Warehouse Management - More granular
  'warehouse.asc.sub_warehouses.create': [
    'super_admin',
    'company_admin',
    'asc_admin',
    'asc_warehouse',
  ],
  'warehouse.asc.sub_warehouses.read': [
    'super_admin',
    'company_admin',
    'asc_admin',
    'asc_coordinator',
    'asc_warehouse',
    'asc_technician',
  ],
  'warehouse.asc.sub_warehouses.update': [
    'super_admin',
    'company_admin',
    'asc_admin',
    'asc_warehouse',
  ],
  'warehouse.asc.sub_warehouses.delete': [
    'super_admin',
    'company_admin',
    'asc_admin',
  ],

  // Sub-Warehouse Accessory Management
  'warehouse.asc.sub_warehouses.accessories.add': [
    'super_admin',
    'company_admin',
    'asc_admin',
    'asc_warehouse',
  ],
  'warehouse.asc.sub_warehouses.accessories.update': [
    'super_admin',
    'company_admin',
    'asc_admin',
    'asc_warehouse',
  ],
  'warehouse.asc.sub_warehouses.accessories.remove': [
    'super_admin',
    'company_admin',
    'asc_admin',
    'asc_warehouse',
  ],

  // Sub-Warehouse Stock Operations
  'warehouse.asc.sub_warehouses.stock.read': [
    'super_admin',
    'company_admin',
    'asc_admin',
    'asc_coordinator',
    'asc_warehouse',
    'asc_technician',
  ],
  'warehouse.asc.sub_warehouses.stock.transactions': [
    'super_admin',
    'company_admin',
    'asc_admin',
    'asc_coordinator',
    'asc_warehouse',
  ],

  // Common data access - Updated with new role structure
  'common.read': [
    'super_admin',
    'company_admin',
    'general_warehouse_manager',
    'admin_level_1',
    'asc_admin',
    'asc_manager',
    'asc_coordinator',
    'asc_technician',
    'asc_warehouse',
    'company_customer_service',
    'call_center',
  ],
} as const satisfies Record<string, RoleType[]>;
